<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CPLSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('c_p_l_s')->delete();

        DB::table('c_p_l_s')->insert([
            ['id' => 1, 'kode' => 'S1', 'kategori' => 'S', 'sub_kategori' => 'Sikap dan Tata Nilai', 'deskripsi' => "Bertaqwa kepada Tuhan Yang Maha Esa dan mampu menunjukkan sikap\nreligius;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:42:18'],
            ['id' => 2, 'kode' => 'S2', 'kategori' => 'S', 'sub_kategori' => 'Sikap dan Tata Nilai', 'deskripsi' => "Menjunjung tinggi nilai kemanusiaan dalam menjalankan tugas berdasarkan\nagama, moral, dan etika;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:42:28'],
            ['id' => 3, 'kode' => 'S3', 'kategori' => 'S', 'sub_kategori' => 'Sikap dan Tata Nilai', 'deskripsi' => "Berkontribusi dalam peningkatan mutu kehidupan bermasyarakat, berbangsa,\nbernegara, dan kemajuan peradaban berdasarkan Pancasila;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:42:36'],
            ['id' => 4, 'kode' => 'S4', 'kategori' => 'S', 'sub_kategori' => 'Sikap dan Tata Nilai', 'deskripsi' => "Berperan sebagai warga negara yang bangga dan cinta tanah air, memiliki\nnasionalisme serta rasa tanggungjawab pada negara dan bangsa;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:42:50'],
            ['id' => 5, 'kode' => 'S5', 'kategori' => 'S', 'sub_kategori' => 'Sikap dan Tata Nilai', 'deskripsi' => "Menghargai keanekaragaman budaya, pandangan, agama, dan kepercayaan, serta pendapat atau temuan orisinal orang lain;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:43:01'],
            ['id' => 6, 'kode' => 'S6', 'kategori' => 'S', 'sub_kategori' => 'Sikap dan Tata Nilai', 'deskripsi' => "Bekerjasama dan memiliki kepekaan sosial serta kepedulian terhadap masyarakat\ndan lingkungan;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:43:10'],
            ['id' => 7, 'kode' => 'S7', 'kategori' => 'S', 'sub_kategori' => 'Sikap dan Tata Nilai', 'deskripsi' => "Taat hukum dan disiplin dalam kehidupan bermasyarakat dan bernegara;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:43:25'],
            ['id' => 8, 'kode' => 'S8', 'kategori' => 'S', 'sub_kategori' => 'Sikap dan Tata Nilai', 'deskripsi' => "Menginternalisasi nilai, norma, dan etik akademik;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:43:48'],
            ['id' => 9, 'kode' => 'S9', 'kategori' => 'S', 'sub_kategori' => 'Sikap dan Tata Nilai', 'deskripsi' => "Menunjukkan sikap bertanggungjawab atas pekerjaan di bidang keahliannya\nsecara mandiri;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:44:05'],
            ['id' => 10, 'kode' => 'S10', 'kategori' => 'S', 'sub_kategori' => 'Sikap dan Tata Nilai', 'deskripsi' => "Menginternalisasi semangat kemandirian, kejuangan, dan kewirausahaan;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:44:28'],
            ['id' => 11, 'kode' => 'P1', 'kategori' => 'P', 'sub_kategori' => 'Pengetahuan', 'deskripsi' => "Menguasai konsep-konsep matematika untuk memecahkan berbagai masalah yang berkaitan dengan logika, prinsip-prinsip pemodelan matematika, program linear, metode numerik, struktur diskrit, ilmu probabilitas, dan statistika;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:59:15'],
            ['id' => 12, 'kode' => 'P2', 'kategori' => 'P', 'sub_kategori' => 'Pengetahuan', 'deskripsi' => "Menguasai teori dan konsep yang mendasari ilmu komputer;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:59:27'],
            ['id' => 13, 'kode' => 'P3', 'kategori' => 'P', 'sub_kategori' => 'Pengetahuan', 'deskripsi' => "Menguasai prinsip algoritma dan logika pemrograman yang dapat digunakan\ndalam pemodelan dan desain sistem berbasis komputer;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:59:58'],
            ['id' => 14, 'kode' => 'P4', 'kategori' => 'P', 'sub_kategori' => 'Pengetahuan', 'deskripsi' => "Memahami konsep dan paradigma bahasa pemrograman komputer, dan penerapannya dalam menyelesaikan berbagai permasalahan sederhana, serta membandingkan berbagai solusi;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 13:00:35'],
            ['id' => 15, 'kode' => 'P5', 'kategori' => 'P', 'sub_kategori' => 'Pengetahuan', 'deskripsi' => "Memahami teori dasar arsitektur komputer dan jaringan komputer, termasuk perangkat keras komputer dan jaringan;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 13:00:51'],
            ['id' => 16, 'kode' => 'P6', 'kategori' => 'P', 'sub_kategori' => 'Pengetahuan', 'deskripsi' => "Menguasai metodologi pengembangan sistem, yaitu perencanaan, desain, penerapan, pengujian dan pemeliharaan sistem;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 13:01:20'],
            ['id' => 17, 'kode' => 'P7', 'kategori' => 'P', 'sub_kategori' => 'Pengetahuan', 'deskripsi' => "Menentukan pendekatan sistem cerdas yang sesuai dengan problem yang\ndihadapi, memilih representasi pengetahuan dan mekanisme penalarannya.", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 13:01:52'],
            ['id' => 18, 'kode' => 'P8', 'kategori' => 'P', 'sub_kategori' => 'Pengetahuan', 'deskripsi' => "Menguasai algoritma dan pemrograman untuk memanipulasi data, grafis, citra,\nsuara, rendering, animasi, visualisasi, dan multimedia; dan", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 13:01:46'],
            ['id' => 19, 'kode' => 'P9', 'kategori' => 'P', 'sub_kategori' => 'Pengetahuan', 'deskripsi' => "Memahami konsep pengolahan data untuk menghasilkan tren dan pola dalam\nsebuah data.", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 13:02:05'],
            ['id' => 20, 'kode' => 'KU1', 'kategori' => 'KU', 'sub_kategori' => 'Keterampilan Umum', 'deskripsi' => "Mampu mengembangkan pemikiran logis, kritis, sistematis, dan kreatif melalui\npenelitian ilmiah, penciptaan desain atau karya seni dalam bidang ilmu\npengetahuan dan teknologi yang memperhatikan dan menerapkan nilai\nhumaniora sesuai dengan bidang keahliannya, menyusun konsepsi ilmiah dan\nhasil kajian berdasarkan kaidah, tata cara, dan etika ilmiah dalam bentuk tesis\natau bentuk lain yang setara, dan diunggah dalam laman perguruan tinggi, serta\nmakalah yang telah diterbitkan di jurnal ilmiah terakreditasi atau diterima di jurnal internasional;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:44:44'],
            ['id' => 21, 'kode' => 'KU2', 'kategori' => 'KU', 'sub_kategori' => 'Keterampilan Umum', 'deskripsi' => "Mampu melakukan validasi akademik atau kajian sesuai bidang keahliannya\ndalam menyelesaikan masalah di masyarakat atau industri yang relevan melalui pengembangan pengetahuan dan keahliannya;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:45:01'],
            ['id' => 22, 'kode' => 'KU3', 'kategori' => 'KU', 'sub_kategori' => 'Keterampilan Umum', 'deskripsi' => "Mampu menyusun ide, hasil pemikiran, dan argumen saintifik secara\nbertanggung jawab dan berdasarkan etika akademik, serta mengkomunikasikannya melalui media kepada masyarakat akademik dan masyarakat luas;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:45:12'],
            ['id' => 23, 'kode' => 'KU4', 'kategori' => 'KU', 'sub_kategori' => 'Keterampilan Umum', 'deskripsi' => "Mampu mengidentifikasi bidang keilmuan yang menjadi obyek penelitiannya\ndan memposisikan ke dalam suatu peta penelitian yang dikembangkan melalui pendekatan interdisiplin atau multidisiplin;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:45:40'],
            ['id' => 24, 'kode' => 'KU5', 'kategori' => 'KU', 'sub_kategori' => 'Keterampilan Umum', 'deskripsi' => "Mampu mengambil keputusan dalam konteks menyelesaikan masalah pengembangan ilmu pengetahuan dan teknologi yang memperhatikan dan menerapkan nilai humaniora berdasarkan kajian analisis atau eksperimental terhadap informasi dan data;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:45:55'],
            ['id' => 25, 'kode' => 'KU6', 'kategori' => 'KU', 'sub_kategori' => 'Keterampilan Umum', 'deskripsi' => "Mampu mengelola, mengembangkan dan memelihara jaringan kerja dengan kolega, sejawat di dalam lembaga dan komunitas penelitian yang lebih luas;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:46:14'],
            ['id' => 26, 'kode' => 'KU7', 'kategori' => 'KU', 'sub_kategori' => 'Keterampilan Umum', 'deskripsi' => "Mampu meningkatkan kapasitas pembelajaran secara mandiri; dan", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:47:14'],
            ['id' => 27, 'kode' => 'KU8', 'kategori' => 'KU', 'sub_kategori' => 'Keterampilan Umum', 'deskripsi' => "Mampu mendokumentasikan, menyimpan, mengamankan, dan menemukan\nkembali data hasil penelitian dalam rangka menjamin kesahihan dan mencegah\nplagiasi.", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:47:29'],
            ['id' => 28, 'kode' => 'KK1', 'kategori' => 'KK', 'sub_kategori' => 'Keterampilan Khusus', 'deskripsi' => "Menerapkan metodologi pengembangan sistem, yaitu perencanaan, desain,\npenerapan, pengujian dan pemeliharaan sistem;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:48:49'],
            ['id' => 29, 'kode' => 'KK2', 'kategori' => 'KK', 'sub_kategori' => 'Keterampilan Khusus', 'deskripsi' => "Merancang dan mengembangkan sistem penyimpanan data mulai dari skema\ndata, relasi data, penyimpanan yang efisien, dan pemeliharaan sistem\npenyimpanan data;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:49:02'],
            ['id' => 30, 'kode' => 'KK3', 'kategori' => 'KK', 'sub_kategori' => 'Keterampilan Khusus', 'deskripsi' => "Merancang dan mengembangkan environment sistem secara utuh, termasuk di dalamnya pemilihan topologi, hardware, middleware, dan software yang sesuai\ndengan kebutuhan;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:49:17'],
            ['id' => 31, 'kode' => 'KK4', 'kategori' => 'KK', 'sub_kategori' => 'Keterampilan Khusus', 'deskripsi' => "Mengembangkan rancangan solusi untuk menyelesaikań permasalahan di\nbidang Informatika, mengukur kinerja suatu rancangan solusi, serta dapat mengumpulkan, mengolah, dan menyajikan data dengan akuntabel;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:49:34'],
            ['id' => 32, 'kode' => 'KK5', 'kategori' => 'KK', 'sub_kategori' => 'Keterampilan Khusus', 'deskripsi' => "Mampu mengembangkan perangkat lunak tepat guna yang bernilai ekonomis\ndan berdaya jual;", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:49:53'],
            ['id' => 33, 'kode' => 'KK6', 'kategori' => 'KK', 'sub_kategori' => 'Keterampilan Khusus', 'deskripsi' => "Merancang dan mengembangkan suatu sistem cerdas baik melalui basis\npengetahuan maupun yang diperoleh melalui pembelajaran mesin; dan", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:50:07'],
            ['id' => 34, 'kode' => 'KK7', 'kategori' => 'KK', 'sub_kategori' => 'Keterampilan Khusus', 'deskripsi' => "Mampu menganalisis dan menyajikan data beserta polanya secara visualisasi\nsehingga mudah dipahami oleh pengguna ataupun proses lain menggunakan alat bantu.", 'created_at' => '2025-11-06 09:41:10', 'updated_at' => '2025-12-11 12:50:19'],
        ]);
    }
}